"""User profile pic length

Revision ID: 4a1036e508b6
Revises: e2462e2de86b
Create Date: 2023-03-04 15:39:23.159947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1036e508b6'
down_revision = 'e2462e2de86b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
        existing_type=sa.String(length=64),
        type_=sa.String(length=1024),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
        existing_type=sa.String(length=1024),
        type_=sa.String(length=64),
        existing_nullable=False)
    # ### end Alembic commands ###
