"""User profile pic length

Revision ID: ee9ce6b92b5b
Revises: e2462e2de86b
Create Date: 2023-03-04 15:32:20.046807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9ce6b92b5b'
down_revision = 'e2462e2de86b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
