[tool.poetry]
name = "tt-colmap"
version = "0.1.0"
description = ""
authors = ["jonlee48 <jonathan.lee48@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
